version: '3'
services:
  web:
    image: nginx
    ports:
      - "80:80"
  
  qbittorrent:
    image: linuxserver/qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
   
    ports:
      - "8085:8080"
  
